### ISSUE TITLE
0.8.9 - Update error...

### ISSUE THREAD

**Issue by mxpowe** [raveberry/raveberry#109]
Was running I believe 8.6 then did the update from within settings.
Now says im running 8.9 but still prompts me to do the update... and when I click update it says "only available in full install"

![image](https://user-images.githubusercontent.com/63602731/116934501-1032b400-ac33-11eb-987c-308f92dfb7f9.png)

**Comment by mxpowe** [comment]
So I ssh into the pi, checked the logs...
PLAY RECAP *********************************************************************
localhost                  : ok=56   changed=16   unreachable=0    failed=0    skipped=76   rescued=0    ignored=0


    Finished!

    Raveberry was successfully installed.
    You can now visit http://raveberry/

**Comment by mxpowe** [comment]
Nevermind, it looks like it was a browser cache issue, I cleared my cache and everything is fine.... except... you removed the Github link from settings lol

**Comment by raveberry** [comment]
Yeah, I (finally) changed all frontend ids to use kebab-case. This has been bothering me more than it should. As a result, the css does not match the old cached pages and a cache refresh is necessary.
I replaced the github link with a link to the new website, because I wanted to link more stuff (github, reddit, website) and with icons for all of them the menu would be too overcrowded. Since everything is linked on the website anyway I chose to only show that link.
Two links should be fine, though. So if you think the Github link should remain I could add it back in.
