### ISSUE TITLE
Stream Drop Down Not Working

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#110]
I recently update my docker install and noticed the embed stream in dropdown option. When enabled it appears on the main screen as expected but when I click it it turns red and nothing can be heard - see below:

![image](https://user-images.githubusercontent.com/1932078/118145701-7d80da80-b3d3-11eb-8f79-0e420d6b7201.png)

On your demo install this works great and music can be heard through the browser but I notice your icon stays white. I have a feeling I need to enable something else in my config or docker-compose but not sure what as it appears to ok.

Any suggestions?

Edit: I'm getting same in docker on my NAS and on a Raspberry Pi 4b

**Comment by raveberry** [comment]
Sorry for the delay.

The embedded stream only works for music from Jamendo. The reason is that it offers public streaming links to their songs. This means that every client visiting the demo streams its music directly from Jamendo's server. The music does not need to go through the demo server, reducing the required bandwidth.

This also means that this stream works differently than `/stream`. While `/stream` simply outputs what Raveberry is playing right now, the embedded stream has some client side logic to sync its progress to that of the server. So it can't be trivially repurposed to play `/stream`.

Still, it should be possible to add an option changing this behavior to make the embedded icon play music from `/stream`. Would you make use of that feature?

**Comment by MickyGX** [comment]
I would definitely make use of this feature as I sort of do already. I have added a stream button manually to musiq.html file so my friends only need the one page open to stream.

**Comment by raveberry** [comment]
Right, now I remember #34! Sorry, a lot of things happened in the meantime.

I will add an option to make the button play music from `/stream`. I will also make it the default, since the streaming button then works for all music platforms.

**Comment by raveberry** [comment]
I just released 0.8.12 which makes it possible to listen to `/stream` with the speaker icon. It would be great if you could test if it works for you.

**Comment by MickyGX** [comment]
Sorry for the major dely in getting back to you but I have been overseas for a few months. Just updated to the latest version 0.9 and tried this and it doesn't seem to be working. Only tested on docker version NOT on rasberry Pi yet. Not sure if its supposed to work on both

**Comment by MickyGX** [comment]
As a follow up, this is now working. For whatever reason icecast stopped working on a previously working docker-compose file. I redid the compose file as per the new reworked docker-compose and it is now working :)

**Comment by raveberry** [comment]
Great to hear! Thanks for testing it out.
