### ISSUE TITLE
Question about function of icons

### ISSUE THREAD

**Issue by DanielVolz** [raveberry/raveberry#113]
I'm sorry if this is obvious but I read the documentation and I can't find an answer to this.

What do this icons do on click?
And what does "please enable playlist to use this" mean?

Thank you very much for this project!

![Screenshot_20210819-204525.jpg](https://user-images.githubusercontent.com/3275994/130128479-5e0bb5b0-c115-421e-8770-976fabf53ecc.jpg)

**Comment by raveberry** [comment]
Unfortunately these icons are not as obvious as I would like them to be. I did not yet write proper documentation because I wasn't sure if the interface will stay the way it is and I didn't want to do the work twice. Given the fact it didn't change substantially since release I should probably finally bring myself to do it…

Until then, here is a short description for each icon that could be visible:
![icons](https://user-images.githubusercontent.com/53476237/130354004-d993e549-bd66-44a4-978c-c9ab66d42afd.png)
1: Go back to Raveberry's main page
2: Open the input field to add a new hashtag. Tap again to send the hashtag (or abort if empty)
3: Open/close the dropdown menu.
4: Not a button. Shows how many users are currently active on the page (technically: were active the last 30 minutes).
5: Switch between light and dark mode.
6: Open /settings.
7: Enable the last configuration of visualization without visiting /lights. Tap again to disable all visualization. Yellow if active.
8: Open /lights.
9: Open /network_info.
10: Visit raveberry.party.
11: Choose your preferred music platform that is searched first for requested songs. Configurable by each user independently.
12: Download shareberry.apk.
13: Open /stream.
14: Enable playlist mode. Required for actions that affect multiple songs. Lighter shade of grey if enabled. Tap again to disable.
15: Prefill the search box with a random song that was previously requested. Prefills with playlists if playlist mode is active.
16: Search for the given input and enqueue the first search result. Enqueues a whole playlist if playlist mode is active. After pressing 15, this changes to an arrow, indicating that no search is performed, but a previous result is enqueued.
17: Pressing this will play the music currently played by Raveberry on the device visiting the website. Needs to be enabled in settings and requires /stream to be active or musiq from Jamendo.
18: Restart the current song.
19: Seek 10 seconds backwards.
20: Play/Pause the current song.
21: Seek 10 seconds forwards.
22: Skip the current song.
23: Enable shuffle mode. If enabled, selects a random song from the queue instead of the first one. Only available when not voting.
24: Enable repeat mode. Played songs are enqueued again at the end of the queue.
25: Autoplay. When the last song is dequeued, another song is enqueued based on the last song.
26: Auto-Playlist. Enqueue a playlist based on the currently playing song. Requires playlist mode to be active.
27: Not a button. Shows the cumulative time of all songs in the queue.
28: Not a button. The slider controls the volume of Raveberry.
29: Shuffle all. Randomly reorders all songs in the queue. When voting, does not occur across songs with different vote count. Requires playlist mode to be active.
30: Remove all. Deletes all songs from the queue. Requires playlist mode to be active.

Hope that helps!

**Comment by DanielVolz** [comment]
Thanks for the detailed reply! Great addition to the documentation.
