### ISSUE TITLE
Could not open playback device 'default'

### ISSUE THREAD

**Issue by esturniolo** [raveberry/raveberry#114]
Hi!
I was trying to make this work in docker without luck.
As I seen in the logs, Modipy can't open the sound device:

```
INFO     2021-09-10 20:13:35,398 [7:HttpServer] mopidy.internal.path
  Creating dir file:///var/lib/mopidy/.local/share/mopidy/http
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': No such file or directory
WARNING  2021-09-10 20:14:08,765 [7:MainThread] mopidy.audio.gst
  GStreamer warning: Failed to connect: Connection refused
```

I tried too commenting this line:

```
 # Comment this line if pulse does not work.
      - "/run/user/${UID:-1000}/pulse:/run/user/105/pulse"
```
But I've the same results.

The rest of the app seems to works, but I can't hear nothing.

Running from on Ubuntu server 20.04 as docker container and tested from two different devices (in the same network)

Any idea?

BTW I don't understand fully how it works for the people, but I think that this kind of question can be asked in the Reddit sub.

**Comment by raveberry** [comment]
Does your system have a working sound output? If it is not connected to a speaker, you would need to use the streaming setup from `icecast.docker-compose.yml `, which does not require any local playback devices.

 I'm not sure, but maybe pulseaudio is not even installed on Ubuntu Server. To check if it is working, you can use `paplay /usr/share/sounds/alsa/Front_Center.wav`. Replace `paplay` with `aplay` to test alsa. At least one of them needs to work for the default `docker-compose.yml` to be usable.

I prefer Github for issues because I get notified and it is more easily searchable. Reddit is mostly used for announcements and discussions. I do check both though, so you can use whichever is more comfortable for you.

**Comment by esturniolo** [comment]
Oh... I see. So here is where I need to understand how it works, because I though that the IceCast compose was something related to online radio.


Here is the output of paplay and aplay. We can see that there is nothing that manage sound in the system.
 ```
eas@server:~$ paplay /usr/share/sounds/alsa/Front_Center.wav

Command 'paplay' not found, but can be installed with:

sudo apt install pulseaudio-utils

eas@server:~$ aplay /usr/share/sounds/alsa/Front_Center.wav

Command 'aplay' not found, but can be installed with:

sudo apt install alsa-utils
```

Ok with it. Don't worry. This was only for testing in my own local environment.

I think that you know Festify.us and with this I tried to emulate that service.
So should I use the icecast compose for that?

My goal is to put this online and anybody in the world can participate voting and from my home stream it to a online radio station.
So the people just need to vote but not to listen, while I (the admin) should be the only one able to listen what the people vote.

Is that possible?

**Comment by raveberry** [comment]
It depends on where your service should run. If you want to use a remote server, you should use the icecast compose file. This is also used by the demo page.

If you only want to locally play music, you can consider using a system install or the "normal" docker-compose file. This would circumvent #47. You could then use a reverse ssh-tunnel to connect to your server (remote feature), so everybody can access your instance.

**Comment by esturniolo** [comment]
I'll check it out.

thanks!
