### ISSUE TITLE
system install fails on Copy Raveberry files to the remote

### ISSUE THREAD

**Issue by brantje** [raveberry/raveberry#115]
Hi,
Thank you for making this awesome project.
On install i'm getting:
```
TASK [Copy Raveberry files to the remote] **********************************************************************************************

fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --no-owner --no-group --include=static/*.js --include=static/*.css --include=static/*.woff2 --exclude=.git --filter=dir-merge,- .gitignore --out-format='<<CHANGED>>%i %n%L' /home/pi/.local/lib/python3.7/site-packages/raveberry/setup/../ /opt/raveberry/", "msg": "unexpected end of filter rule: dir-merge,-\nrsync error: syntax or usage error (code 1) at exclude.c(1040) [client=3.1.3]\n", "rc": 1}
```
Looks like the rsync parameters are incorrect.

**Comment by brantje** [comment]
Seems to be related to this line: https://github.com/raveberry/raveberry/blob/master/setup/system_install.yaml#L47

**Comment by raveberry** [comment]
Possibly related to #112.

Unfortunately I can not reproduce this on my system. Adding quotes to the `--filter` argument sounds like the solution but breaks it for me. 
Could you tell me which versions are installed on your system?
```
rsync --version
ansible-playbook --version
```
I assume you are on a Raspberry Pi, what are you using (Hardware and OS)?

**Comment by brantje** [comment]
rsync  version 3.1.3  protocol version 31
ansible-playbook [core 2.11.5]
Running on Rpi 4. 
I have removed ` - "--filter=dir-merge,- .gitignore"`  and it works perfectly, except for the Soundcloud integration, which gives me a 500 error on adding songs.

With the shutdown of Groovy and Rythm, you have a very nice replacement of those bots :).
Also, where is the donate button?

**Comment by Dany286** [comment]
hi, 
i have the same issue. When i removed `- "--filter=dir-merge,- .gitignore` i have an other issue later : 

`TASK [Create raveberry user] ***************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (psycopg2) on LaLorgnette's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}`

`rsync  version 3.1.3  protocol version 31`
`ansible-playbook [core 2.11.5]`

Raspberry 3B with Raspberry os  `Linux LaLorgnette 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l GNU/Linux`

Thanks.

**Comment by raveberry** [comment]
In the update to [ansible 4.5.0](https://github.com/ansible-community/ansible-build-data/blob/main/4/CHANGELOG-v4.rst#ansible-posix), ansible.posix was updated to 1.3.0, which includes a fix for [this issue](https://github.com/ansible-collections/ansible.posix/issues/190). This changes the way quotes are handled.
In 4.4.0, quotes (`- "--filter='dir-merge,- .gitignore'"`) lead to `Unknown filter rule`. With 4.5.0, omitting quotes leads to `unexpected end of filter rule`.
So I added quotes and required ansible 4.5 for new installs. With Raveberry 0.9.1 you should be good to go now, thanks for raising the issue.

Soundcloud recently changed its API, so it's possible that it currently doesn't work with Raveberry. I wasn't sure how many people actually use this feature, so I did not investigate. If I find some time, I will look into it.

Since you are not the first person asking for a donation button, I added a link to my Paypal. If you want to, you can now buy me a beer :).

@Dany286 This sounds like a different problem. Please open a new issue.
It looks like `psycopg2` (python postgres module) is not installed in the python version used by ansible. Which is weird, because one of the first steps of the system installation is installing the dependencies. The outputs of `pip freeze` and `sudo pip freeze` should help finding the cause.

**Comment by brantje** [comment]
> Soundcloud recently changed its API, so it's possible that it currently doesn't work with Raveberry. I wasn't sure how many people actually use this feature, so I did not investigate. If I find some time, I will look into it.

Already did that :). They now require an [oAuth](https://developers.soundcloud.com/blog/security-updates-api) token.
So basically we need to be able to enter our user/pass + app secret/token. 
Unfortunately registering a new app is at the moment not possible yet.

**Comment by raveberry** [comment]
I created #117 for the Soundcloud problem.
Please reopen this issue if the rsync-fix did not work.
