### ISSUE TITLE
Enhancement: Allow admin to deactivate downvotes and disallow user to remove or move up song when voting is deactivated.

### ISSUE THREAD

**Issue by Snorkell** [raveberry/raveberry#127]
Hello,
A friend of mine is using Raveberry in his bar, and he wanted to tell you thank you so much for this project.
While using Raveberry, we had some people trolling in the bar by downvoting in group lots of music just to annoy everyone else, so we decided to deactivate voting, but the they can just move music at the top of the queue or simply remove them.

So the purpose of this post is to know if it would be possible, via some options, to not give the possibility for the anonymous users to remove/move songs when voting is disabled and if possible at the same time, to allow admins to just deactivate downvotes in case of people trolling.

And by the way this project is pure gold, thank you so much for this !
looking forward for new updates

**Comment by raveberry** [comment]
Hi, awesome that you like it!
I think that's a great idea. I would probably extend the current voting/no voting into multiple options of varying interactivity. I think these four would make sense:
* full public control. current "no voting", everybody can delete and reorder all songs
* up- and downvotes. current "voting"
* upvotes only. prevents people from downvoting all songs that are not theirs
* no control. songs can only be pushed, but their order can only be changed by mod/admin users.

I will put this into Raveberry with the next update. Do you have any comments / suggestions?
Also as a hint: there is the "IP checking" feature which checks votes on the server side and prevents the same device from voting for the same song twice. Maybe this could prevent some trolling in your case.

**Comment by Snorkell** [comment]
Hi, thanks for your feedback on this enhancement idea.
I have a suggestion, when looking at the code, I saw that you have implemented an api for posting songs to the backend.
I think having more endpoints that allows more control on the application would be nice. for exemple, a route to pause/play the music, an enpoint to skip music, and so on. This will allow developpers to implement their own custom interface without creating issues when they need something UI related

**Comment by raveberry** [comment]
Sorry, I thought I already answered.
The different levels of interactivity are now part of Raveberry with 0.10.5, thanks for the suggestion.

Regarding the API: Currently it only contains the `api/post-song` url, because I needed that for [shareberry](https://github.com/raveberry/shareberry/). The [Discord bot](https://github.com/raveberry/discord/) uses some more exposed endpoints that are not part of the "official" API (yet), like `/ajax/musiq/vote`. Maybe some of that might help you.

I agree that having a defined interface would be a good idea, though. I'll add it to my list.
