### ISSUE TITLE
'raveberry install' crashes on TASK [Migrate database]

### ISSUE THREAD

**Issue by MarkTheGoose** [raveberry/raveberry#130]
Hi, I've tried to self-help, but stumbled here ^

Clean install of Raspbian 11 (bullseye) 5.15.32-v7+ (32bit with graphics, but without clutter) on Raspberry Pi 3 Model B Rev 1.2. Python3.9. Installed all dependencies, including those mentioned in [raveberry]/CONTRIBUTING.md.

I made two changes to /home/pi/.local/lib/python3.9/site-packages/raveberry/config/raveberry.yaml

- Disabled YouTube, Enabled Spotify (although, I now see that's currently broken)
- Changed hostname to 'jukebox.party'

Install script (v0.10.5) proceeds to **TASK [Migrate database]** with no errors. /opt/raveberry/logs/error.log shows no related errors. Postgres is running and database raveberry exists, but \dt reports "Did not find any relations."

`cd /opt/raveberry && sudo -Hu www-data DJANGO_MOCK=1 FORCE_POSTGRES=1 python3 manage.py migrate
`
gives the error message:

`FileExistsError: [Errno 17] File exists: '/usr/local/lib/python3.9/dist-packages/django/contrib/admin/static/admin' -> '/opt/raveberry/static/admin'`

**Comment by MarkTheGoose** [comment]
I found a workaround. With two terminal windows, one running 'raveberry install', if I wait for the ansible script to get to **TASK [Enable and restart pulseaudio]** and then in the second terminal:

`sudo rm /opt/raveberry/static/admin`

... the install script completes successfully. I'm no python expert, but the code where it fails is line 221 in /opt/raveberry/main/settings.py and this all looks OK to me ...

```
# Static files (CSS, JavaScript, Images)
STATIC_FILES = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS: List[str] = [STATIC_FILES]
STATIC_URL = "/static/"

if not os.path.exists(os.path.join(BASE_DIR, "static/admin")):
    import django

    DJANGO_PATH = os.path.dirname(django.__file__)
    STATIC_ADMIN = os.path.join(DJANGO_PATH, "contrib/admin/static/admin")
    if not DOCKER:
        # create symlink to admin static files if not present
        # In the docker setup, the nginx container includes the static files on build
        os.symlink(
            STATIC_ADMIN,
            os.path.join(BASE_DIR, "static/admin"),
            target_is_directory=True,
        )
        print("linked static admin files")

# channels
ASGI_APPLICATION = "main.routing.APPLICATION"
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [(REDIS_HOST, REDIS_PORT)], "capacity": 1500, "expiry": 10},
    }
}
```

**Comment by raveberry** [comment]
Thanks for your very thorough bug report, additional information like this always helps finding the issue!

In this case however, I was unfortunately not able to replicate the bug. I tried it on both a Pi 3 and a Pi 4 with newest Bullseye but the installation ran through without errors.
I don't understand why that task would fail, especially since the code checks for the existence of the link right before creating it. The only thing I can think of right now would be a race condition with another process that creates the file at the same time? This seems very unlikely, though.
Did you try to install Raveberry more than once? Did the error occur every time?

**Comment by MarkTheGoose** [comment]
Reply. I tried the install twice as it was setup and it happened both times. The only bit I didn’t mention was that I initially tried the ‘Raveberry Run’ approach, but part way through, killed it and went for ‘Raveberry Install’ instead. To be fair, once the file was deleted, the problem went away. I have subsequently tried it myself twice using both a Raspberry 3 & 4 (clean installs of OS, as above) and have been unable to reproduce it myself, and as you say, the code should check for the existence of ‘admin’ and move on…

In reinstalling from fresh, I did encounter a problem that I encounter every time. Part way through the Install Python dependencies, it gets hung up on the fact that apt has installed Python yaml (it gets installed as a dependency by ‘sudo apt install -y python3-pip mopidy redis-server ffmpeg gstreamer1.0-plugins-bad’). Simply resolved by issuing ‘sudo apt remove -y python-yaml’. Not sure if this is also unique to my config. I can reproduce this and provide a more detailed sequence of steps if it’s helpful?

Quick additional question, once I’ve scanned the music folder and it’s found (say) 5,000 music files on an external USB, is there a quick way to remove them all if I want to use a completely different set of music files on a different external USB and rescan them. I tried using http://raveberry.local/admin to delete archived songs, but whilst it was happy removing 100, it didn’t like removing 5,000 and always arrived at an error page. How about a button in the Local Files section to delete all local files from the database?

Apologies, if I should really be raising 2 more issues for these supplementary points - I’m not very familiar with git etiquette…

**Comment by raveberry** [comment]
Ok, so it really seems to be kind of dodgy. If it really is only a race condition, I will fix it by using a try/catch instead of the check and link which is used now.

As for the pyyaml, on my system it is not installed as a dependency. I ran into this error before though, it can be quite annoying. Removing the apt package before installing the pip version should fix it.

Regarding your local music library, there is a way to delete all local songs from your db:
`cd /opt/raveberry && sudo -iu www-data python3 manage.py shell`
and then paste
```
from core.models import ArchivedSong, ArchivedPlaylist

for playlist in ArchivedPlaylist.objects.all():
    if playlist.entries.first().url.startswith("local_library"):
        print(playlist)
        playlist.delete()
for song in ArchivedSong.objects.all():
    if song.url.startswith("local_library"):
        print(song.url)
        song.delete()
```
Since you are not the first person to ask for it though, I will probably add such a button for convenience.

Opening new issues is usually preferred, but since your points are minor it is completely fine to put them here.

**Comment by MarkTheGoose** [comment]
Fabulous - on all points. I didn’t say it at the start of this exchange, but I think that your software is wonderful, so thank you for all your efforts. That said, I’d love it if somebody finds a way to reconnect it to Spotify - I really miss that feature.
