### ISSUE TITLE
Consider running via docker image

### ISSUE THREAD

**Issue by nickatnight** [raveberry/raveberry#24]
I'm in the process of provisioning my Pi3 with `raveberry`, and the installation is a little mundane. Is there a plan to host a `raveberry` image?

**Comment by raveberry** [comment]
The project interfaces a lot with external components when creating a hotspot, controlling leds via i2c/spi, showing visualization through hdmi, and playing music of course.

I was afraid that configuring all this is not worth the payout in the end, all these components likely would have to be passed through to the container.

However: For testing I started using docker last week, since travis does not offer Ubuntu 20.04. It should not be too hard to extend this container to provide the basic features (webserver and sound output) by mapping a volume and a port. Probably it would be better to use the postgres docker for the database instead of installing it in the image like I do currently for testing.

If you think people will actually use it, I might look into it when I find some time.

**Comment by raveberry** [comment]
There is now the possibility to run Raveberry with docker-compose.
