### ISSUE TITLE
Feature Request: Manual install documentation

### ISSUE THREAD

**Issue by Barborica-Alexandru** [raveberry/raveberry#30]
So I already have a redis and postgres dedicated server so If it would be possible at some point in the future to break down the manual install into configuration sections. The bash scripts are well written so just the actual documentation into how and what to edit is missing. Absolutely no rush, everything is working and if I dive down into the bash scripts I can extract the steps and write up the documentation myself and post it back here, i'm just too lazy right now.

**Comment by raveberry** [comment]
Yes, splitting them down into more configurable parts should be possible. The cleanest solution would probably be to supply a section in the config file for people to specify their postgres and/or redis instances. The script could then either use the default instance if no values were given or the specified one otherwise.

I'm just not sure how many people would benefit from this process being automatic. Since modifying and testing the install scripts for different setups is always time consuming, I'll probably wait until more people are affected.
However, if you come around to changing the scripts and documentation accordingly, I would happily accept contributions.

**Comment by raveberry** [comment]
0.8.0 changed the installation process, an ansible playbook is used instead of bash scripts.

Adding a config read for custom postgres/redis hosts into `main/settings.py` would be an easy addition. If the need still exists, simply open a new issue please.
