### ISSUE TITLE
iframe support

### ISSUE THREAD

**Issue by MickyGX** [raveberry/raveberry#35]
I want to enable iframe support for raveberry so I can include it as part of my website and also add the streaming to the same page. I tried mapping the volume and copying the nginx.conf file over to my local storage but it crashed nginx. Guessing you append or change during install. Can you help?

**Comment by raveberry** [comment]
It's probably easiest for you to include an `<audio>` tag in the `templates/musiq.html` file that sources your stream url. Since you disabled authentication (I think?) this should be pretty straight forward.
In order to incorporate this change in your container, build your own version of the container:
`docker build -f <Dockerfile> -t raveberry/raveberry .`
with this [Dockerfile](https://github.com/raveberry/raveberry/files/4597988/Dockerfile.txt) in the git root.

I don't know how you would solve that by just configuring nginx.

**Comment by MickyGX** [comment]
Apologies in advance outside of some basic docker-compose stuff I'm a noob at the rest of this. So i created a dockerfile in my root of my apps which is where my docker-compose.yml file resides then ran that command above and got:

![image](https://user-images.githubusercontent.com/1932078/81396834-c7adec80-90eb-11ea-9e66-453e2401e55b.png)

Also the other reason I wanted to enable iframes is that I use a software called organizr which embeds all my apps into a nice interface and is password controlled. When I try to embed raveberry it won't because I think the instance of nginx is not set to allow iframes.

**Comment by raveberry** [comment]
You are missing the `.`, which is what docker complains about in this error message. Also, you need to execute this in the cloned raveberry git.
Sorry, but I don't think this problem is related to Raveberry, so please try to find configs that work for you yourself. I don't have the time to give you a step by step solution.
As a general hint: when asking for help, try to always include meaningful information (e.g. the error log from nginx) so other people can better understand your problem.
