### ISSUE TITLE
Fallback Playlists

### ISSUE THREAD

**Issue by Vanixxx** [raveberry/raveberry#39]
[enhancement]Select a (Spotify) Playlist as fallback playlist if there are no votes

**Comment by raveberry** [comment]
How would you imagine this to work? Would this fallback playlist be visible in the queue?

A simple solution would be to just enqueue the playlist, and implement #4. This way, everything users manually put in will prioritize over the playlist. If no such songs are at the top of the queue, the fallback playlist will then be used.
Alternatively, autoplay will always play a suggestion based on the current song if the queue is empty.

**Comment by Vanixxx** [comment]
Yes, the fallback playlist should be visible in the queue and you should be able to vote.
I'm testing Raveberry since yesterday, unfortunately I didn't find a function to add a playlist to the queue.  Is there any help here? Shareberry?
If this is already possible (preferably also with Spotify), my enhancement is obsolete and with #4 everything is ok.
Idea to #4, automatically up-vote when adding a song?

**Comment by raveberry** [comment]
You can add playlists by using the (admittedly rather inconspicuous) button to the left of the dice. If enabled, you will add playlists instead of songs. The number of songs enqueued per playlist defaults to 10, but can be configured in the settings. This works for both Youtube and Spotify.

Auto-upvoting is a good idea, the reason it's not implemented yet is the way Raveberry handles requests. Once the request was sent, there is currently no easy way for the web page to know which song was requested from this device.
However, it is possible to discern manually requested songs from those enqueued by autoplay or through playlists. So an easier way would be to just use that for queue sorting.
I still will look into it, since I like auto-upvoting better, too.

**Comment by raveberry** [comment]
In 0.6.4 I implemented auto-upvoting. Songs queued from playlists start off with zero votes and songs that were explicitly requested receive one vote from the start.
Note that voting mode needs to be enabled, otherwise the votecount will have no effect.

As a bonus it is now also possible to reorder/vote/remove songs that are in download state. This was previously not possible, as they existed only in memory and were not persisted to the queue. With the refactoring required for this feature, they now behave like actual songs with the exception of not (yet) being playable of course.
