### ISSUE TITLE
issue with bluetooth

### ISSUE THREAD

**Issue by mageunic** [raveberry/raveberry#44]
Hi, i'm using raveberry on raspberry Pi 3 B+, I've connect my bluetooth speaker to my Pi but no sound is emitted currently.
before installing raveberry the bluetooth was working correctly but after installation no sound is transmitted. hoping to get some help.
Mageunic

**Comment by raveberry** [comment]
This might have to do with the fact that Raveberry uses system service to run pulseaudio. What is your output for `PULSE_SERVER=127.0.0.1 pactl info` and `PULSE_SERVER=127.0.0.1 pactl list short sinks`?
Also is the `pulseaudio` service running? (`systemctl status pulseaudio`)
Does analog output through the audio jack still work?

The first command should tell you the default output device (which is where sound should be transmitted to). The second one lists all available devices. Maybe they are in a format Raveberry does not recognize. You can change the output device with `PULSE_SERVER=127.0.0.1 pactl set-default-sink <sink-number>`.

The `PULSE_SERVER=127.0.0.1` is needed so `pactl` knows to communicate with the system instance.

**Comment by mageunic** [comment]
for the following command line : PULSE_SERVER=127.0.0.1 pactl info
i get : `Chaîne du serveur : 127.0.0.1
Version du protocole de bibliothèque : 32
Version du protocole du serveur : 32
Local : non
Index client : 0
Tile Size: 65496
Nom d'utilisateur : pulse
Nom d'hôte : raveberry
Nom du serveur : pulseaudio
Version du serveur : 12.2
Spécification d'échantillon par défaut : s16le 2ch 44100Hz
Plan de canaux par défaut : front-left,front-right
Destination par défaut : alsa_output.platform-soc_audio.analog-mono
Source par défaut : alsa_output.platform-soc_audio.analog-mono.monitor
Cookie : d959:145f
`
And for : PULSE_SERVER=127.0.0.1 pactl list short sinks , i get : 
`0	alsa_output.platform-soc_audio.analog-mono	module-alsa-card.c	s16le 1ch 44100Hz	SUSPENDED`

And I see that pulse audio is running

**Comment by raveberry** [comment]
Looks like your bluetooth device is not even connected, `list short sinks` should show something like:
`4	bluez_sink.<addr>.a2dp_sink	module-bluez5-device.c	s16le 2ch 44100Hz	SUSPENDED`
Can you see your device when you scan in the settings page?
What does the page say if you try to connect?

Thanks to this issue I just found and fixed a bug where the `pactl` commands in Raveberry itself were not supplied with the `PULSE_SERVER` environment, I wonder how it ever worked before...
This new version (0.5.11) also adds the possibility to change your output device in the settings page.

Maybe this will help you with your problem.

**Comment by mageunic** [comment]
Yes my Bluetooth speaker is connected to my Pi :
![bluetooth issue](https://user-images.githubusercontent.com/65236802/81930126-681e7800-95e8-11ea-8773-fc3060872fd6.png)

**Comment by mageunic** [comment]
I still have the same problem even with an update( 0.5.11) and a new installation and moreover the music is automatically deleted from the playlist.

**Comment by raveberry** [comment]
The weird thing is that your system is connected to the bluetooth device, but it does not show up in your pulseaudio devices.
Can you check, that the bluetooth module is loaded?
`PULSE_SERVER=127.0.0.1 pactl load-module module-bluetooth-discover`
Should return `Failure: Module initialization failed`
and an error like `Module "module-bluetooth-discover" should be loaded once at most.` should be logged to `/var/log/syslog`.
It might also be related to your full raspbian install. I only tested on the raspbian lite version, if I find time I will install the full version and try it there as well.

The error with your playlists getting deleted:
I assume they are not played at all, just skipped from top to bottem? This sometimes happens if mopidy has an error playing the song, so it continuously skips on to the next one. A simple restart of mopidy (`sudo systemctl restart mopidy`) or in the worst case a system reboot fixes this most of the time. This is most likely unrelated to the bluetooth issue. If it persists, please open a new issue with the logs from mopidy and daphne.

**Comment by mageunic** [comment]
Hi, I'll give you some screenshots :
![bluetooth issue3](https://user-images.githubusercontent.com/65236802/82025283-61980b00-9691-11ea-974c-1fcd241989a4.png)
![bluetooth issue4](https://user-images.githubusercontent.com/65236802/82025291-65c42880-9691-11ea-83b8-390973ec7e2e.png)

For issue of playlist:
I plugged my audio cable in wrong and after a reboot everything's fine.

**Comment by raveberry** [comment]
This looks like the bluetooth module was loaded with the first command, as it did not raise an error there. This module should already be loaded however.
I just found out that Raveberry doesn't actually configure the pulseaudio system instance to load the bluetooth modules. Could you try adding the following lines to `/etc/pulse/system.pa` and reboot afterwards?
```
.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif
```
I copied this from the `default.pa` which is only executed for user instances, but not the system service.

There is also another pulseaudio error in your syslog, but I'm not sure about its significance (the one about `backend-ofono.c`). Since your speaker worked before Raveberry installation, it should be possible to make it work.

**Comment by mageunic** [comment]
Hi, after rewrite line in `/etc/pulse/system.pa` and reboot. I can see my speaker in Output Device but when I select it, Output device changes back to alsa output. 
![bluetooth issue7](https://user-images.githubusercontent.com/65236802/82138553-a357bb80-9821-11ea-88b1-63256e0d402b.png)

Currently, no sound is emitted from the Bluetooth speaker.

**Comment by raveberry** [comment]
Great, that looks like Raveberry now recognizes the speaker! I will add this to the installation process.
What do you mean by selecting: Do you click the bluez device and it instantly selects the first element in the dropdown afterwards, so you can't even set it as the output device?
This might just be a frontend issue, I just need specific info to fix it because I thought I already dealt with this.

There is a good chance that the rest is actually working. You can test it by opening your browsers's console (F12 usually) and running this code:
```
$.post('/ajax/settings/set_output_device/', {
	device: 'bluez_sink.2C_41_A1_96_40_7E.a2dp_sink',
}, function(response) {
	successToast(response);
}).fail(function(response) {
	errorToast(response.responseText);
});
```
This is exactly what the "Set Output Device" button would do if you could select the device, sending the request to the server. The string after device needs to match the element in the dropdown exactly.

As a side note: Don't paste random code into your console just because people tell you to. I know I'm not making a strong point here right after instructing you to do so, but not being careful there can cause serious harm. This time it's ok (I swear) since this is exactly the code that [would have run anyway](https://github.com/raveberry/raveberry/blob/master/static/js/settings.js#L206), just a general heads up.
(sorry for the unnecessary advice if you are experienced with this stuff, I just could not write this without a discaimer)

**Comment by mageunic** [comment]
it works !!!!

**Comment by raveberry** [comment]
v0.6.3: The bluetooth module is now loaded by default and the device selection now works in chrome as well (I only tested it in firefox before).

Thanks for raising the issue. Bluetooth connectivity has been a problem for some time now, and I hope that this finally fixed it.

**Comment by mageunic** [comment]
I just reinstalled raspbian and raveberry and saw that the following lines are not present in `/etc/pulse/system.pa` : 
`.ifexists module-bluetooth-policy.so
load-module module-bluetooth-policy
.endif

.ifexists module-bluetooth-discover.so
load-module module-bluetooth-discover
.endif`

**Comment by raveberry** [comment]
Does the audio output work for bluetooth or is it broken again?
When I tested it, it was sufficient to add this one line: `load-module module-bluetooth-policy`, which should be present.

**Comment by mageunic** [comment]
I have just tested and confirmed that your command line works on its own but it was not present before I modified the file.

**Comment by raveberry** [comment]
that's weird. can you paste the content of the file? Preferably in the state before you modified it.

**Comment by mageunic** [comment]
My  `/etc/pulse/system.pa` without modification : 
#!/usr/bin/pulseaudio -nF
#
# This file is part of PulseAudio.
#
# PulseAudio is free software; you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# PulseAudio is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PulseAudio; if not, see <http://www.gnu.org/licenses/>.

# This startup script is used only if PulseAudio is started in system
# mode.

### Automatically restore the volume of streams and devices
load-module module-device-restore
load-module module-stream-restore
load-module module-card-restore

### Automatically load driver modules depending on the hardware available
.ifexists module-udev-detect.so
load-module module-udev-detect
.else
### Use the static hardware detection module (for systems that lack udev/hal support)
load-module module-detect
.endif

### Load several protocols
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix

### Automatically restore the default sink/source when changed by the user
### during runtime
### NOTE: This should be loaded as early as possible so that subsequent modules
### that look up the default sink/source get the right value
load-module module-default-device-restore

### Automatically move streams to the default sink if the sink they are
### connected to dies, similar for sources
load-module module-rescue-streams

### Make sure we always have a sink around, even if it is a null sink.
load-module module-always-sink

### Automatically suspend sinks/sources that become idle for too long
load-module module-suspend-on-idle

### Enable positioned event sounds
.else
### Use the static hardware detection module (for systems that lack udev/hal support)
load-module module-detect
.endif

### Load several protocols
.ifexists module-esound-protocol-unix.so
load-module module-esound-protocol-unix
.endif
load-module module-native-protocol-unix

### Automatically restore the default sink/source when changed by the user
### during runtime
### NOTE: This should be loaded as early as possible so that subsequent modules
### that look up the default sink/source get the right value
load-module module-default-device-restore

### Automatically move streams to the default sink if the sink they are
### connected to dies, similar for sources
load-module module-rescue-streams

### Make sure we always have a sink around, even if it is a null sink.
load-module module-always-sink

### Automatically suspend sinks/sources that become idle for too long
load-module module-suspend-on-idle

### Enable positioned event sounds
load-module module-position-event-sounds
  load-module module-native-protocol-tcp auth-ip-acl=127.0.0.1
  load-module module-bluetooth-discover

**Comment by raveberry** [comment]
So the bluetooth line was added during the Raveberry installation, but bluetooth playback did not work until you changed it?
Because it's right there at the end of the file.

**Comment by mageunic** [comment]
before I added the line : `load-module module-bluetooth-policy` the bluetooth transmission wasn't working.

**Comment by raveberry** [comment]
Alright, so this line was needed as well, apparently some bluetooth devices require different configuration. With 0.6.4, this line is also added during install.

**Comment by mageunic** [comment]
Hi, it's me again, I have updated raveberry on my RPI with the command line in README.md but the Bluetooth doesn't work anymore. i checked the file : `/etc/pulse/system.pa` and the line `load-module module-bluetooth-policy` is present.

**Comment by raveberry** [comment]
Maybe the stored device were reset with the update.
Were you able to connect the speaker: does it show up if you scan for devices?

**Comment by mageunic** [comment]
I have reboot my RPI today and it works. I don't know why it didn't work yesterday. Sorry for the inconvenience.... Thx for this fix

**Comment by raveberry** [comment]
Sometimes a reboot does magic. Great that it works again.
