### ISSUE TITLE
Trying to test on Ubuntu 18.04.4 LTS, wont start as a service/at boot

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#57]
I've installed raveberry and can run the basic version.  But am having the following issues:

--No idea where the config file is hiding, so I can't add any local music that way (my main focus will be local music as connectivity is sparse where I plan to deploy)

-- when I run 'raveberry system-install, it does it's thing and says I'm good to go, but I can no longer access the web interface, refuses connections.   I looks to have changed my linux host name to 'raveberry' (used to be 'hermes').   Either way my router/dns server gets me there.. I can see other webui's running on the machine.   Just not raveberry. 

I'm a little stuck...  Just checked via lsof, and nothing is running on port 8000

**Comment by raveberry** [comment]
The config file should be located somewhere like `~/.local/lib/python3.7/site-packages/raveberry/config/raveberry.ini`. Usually, `raveberry system-install` prompts you to confirm the config file. Also, local music does not have to be specified at install time, it can be configured after the system install. Actually this is even possible in user-mode (using `raveberry run`).

Raveberry changes the hostname during the system install. The new hostname can be configured in the config file, but defaults to `raveberry`. So if the default config file was used (which was probably the case), the hostname was changed. If you want to change it back, run `sudo hostname hermes` to change it until reboot and edit `/etc/hostname` to persist the change.

I have a nasty suspicion that you installed an old version of raveberry (probably 0.2.4). Ubuntu 18.04 ships with python 3.6 and since 0.3.0 raveberry requires at least python 3.7. So if you installed it with your default installation of pip you have a version that is almost half a year old, and a lot of stuff changed since then.
For example, the port of the user-level server is now 8080 due to a clash with the streaming service icecast.

Unfortunately, performing a system install on Ubuntu 18.04 is quite time-consuming (but possible!), due to mopidy requiring python 3.7. See also the note in the readme. I suggest you use docker instead, that will also work on Ubuntu 18.04, or upgrade your system to Ubuntu 20.04.

**Comment by tiny-e** [comment]
Also, do I need to be root to install it with pip if I'm running as a regular non-root user? (eg, use sudo)

**Comment by raveberry** [comment]
No, you don't. It doesn't matter which user installs the pip package. During system install, you will be prompted for the root password, as it requires sudo privileges.

**Comment by tiny-e** [comment]
Giving it a go now.. fingers crossed.

**Comment by tiny-e** [comment]
welp... something looks borked.  (see here if interested:  https://pastebin.com/mm3TAhik) -- And thank you for your time spent helping out.  May be easier for me to just grab a pi and hook it up somewhere to test... :)

**Comment by raveberry** [comment]
The first error (`ModuleNotFoundError: No module named 'watson'`) appears, because `raveberry` will use your `python3` interpreter by default, which is python 3.6 in your case. The dependencies of the new version are only installed for python 3.7.
To fix this, you could run raveberry with python 3.7 explicitly: `python3.7 ~/.local/bin/raveberry run`.

The second error (`ERROR: A GObject based library was not found.`) however is a lot harder to fix. Mopidy does not support python 3.6, so some workarounds are required. These are described [here](https://mopidy.com/blog/2019/12/27/mopidy-3-faq/#what-about-mopidy-3-on-ubuntu-1804-lts) (which is also linked in the readme).

I would still recommend you to use the docker setup or upgrade your system, as making mopidy 3 work on Ubuntu 18 is not the most straightforward thing. Or use a pi if you have a spare one lying around.

**Comment by tiny-e** [comment]
Decided it was easier to go to a RPi for testing than overhaul my VM (which has other stuff on it).  Closing issue.
