### ISSUE TITLE
System install with different service running on port 80

### ISSUE THREAD

**Issue by iMarv** [raveberry/raveberry#66]
Currently trying to do a `system-install` on a raspberry pi that is already running pi-hole.
Installing fails because nginx cant bind to port 80 as it is already taken (which is fine to me).

I have tried editing `setup/raveberry-static` and `setup/raveberry-events` to use 8080 instead of 80 as the listen port, which did not succeed.

Am I looking in the wrong place or is there a different solution?
I would prefer not to use docker as running docker-compose is a huge hassle.

**Comment by iMarv** [comment]
Problem was the default nginx config created when installing nginx.
After commenting out the listeners on port 80, everything works fine.

**Comment by raveberry** [comment]
Great that you found a solution.
For other people with the same issue: Did you comment out the server block in the default file or delete the default link from sites-enabled?

**Comment by iMarv** [comment]
I commented out the server block in the default nginx config _and_ changed the configs shipped with raveberry (I guess they are being copied into the nginx directory)

**Comment by raveberry** [comment]
Yes, the raveberry files are copied into the directory. I'm just wondering that you had to modify the default config, as it should be [deleted](https://github.com/raveberry/raveberry/blob/master/setup/server.sh#L3) during raveberry's install.

Also, the next upgrade will overwrite the nginx configs again. I could provide a "port" key in the config file so that can be changed.
