### ISSUE TITLE
Use Raveberry with Snapcast?

### ISSUE THREAD

**Issue by champagj** [raveberry/raveberry#77]
Anyone has used snapcast for multi-room audio broadcast that is synced to Raveberry?
Icecast is great but does not offer simultaneous stream.
I have an application where I want to be able to share the raveberry audio stream simultananously in other rooms.

**Comment by raveberry** [comment]
I do not know of anybody. Icecast streams can be opened on multiple client devices, but suffer from buffer latencies.

Since Raveberry uses mopidy, I'm confident that snapcast integration is possible. A quick search results in [this article](https://www.home-assistant.io/blog/2016/02/18/multi-room-audio-with-snapcast/), maybe you can use it for your setup.
The only thing to change on the Raveberry side is probably the mopidy config, so it outputs into a pipe that is read by snapcast instead of directly streaming to an output device.

**Comment by champagj** [comment]
Early testing shows that this works. Running latest full-install of raveberry and used 0.20.0 snapcast server install using pre-built package
sudo apt install </path/to/snapclient_0.x.x_armhf.deb>
I manually changed the mopidy.conf to point the 'audio' to the fifo pipe as recommended in the snapcast config.
After reboot I can hear synched music from Raveberry from a couple android phone running the snapcast client. 
However the audio cuts-off on a regular basis but probably caused by snapcast 0.20.0 as there are a few reports already.
No sound coming out of the pi4 running raveberry as I have not installed/tested the client yet.
Not sure what the best option for volume control will be. Obviously the volumne control on Raveberry does not control the volume output on the stream but each client has individual volume control...
Keep you posted

**Comment by raveberry** [comment]
Thanks for the update, Great that you could make it work!

Raveberry's volume slider initially did change mopidy's volume. I changed the behavior, since previously there was a delay between setting the volume and the change taking effect. If you take a look into `/opt/raveberry/core/musiq/controller.py` you will see the function `set_volume`. The except block is exactly what you want, so you can delete the try block and see if it works (beware of indentation). A `systemctl restart daphne` is required afterwards.

**Comment by mxpowe** [comment]
Im just adding that as chamgp said "No sound coming out of the pi4 running raveberry as I have not installed/tested the client yet.
"
When the client is installed, I do not get audio from Raveberry server locally, it casts good. But when casting the playlist will not continue.

**Comment by raveberry** [comment]
I just tested Raveberry with snapcast and it worked like a charm for me. I will add an option to activate it via Raveberry's UI in the next update.

Do I understand that correctly: you get audio on your snapcast clients, but as soon as the song finishes, the next one is not played?

What client are you using? Are there related error messages in `journalctl -xeu mopidy`, `journalctl -xeu snapserver` or `cat /opt/raveberry/error.log`?

**Comment by mxpowe** [comment]
When I enable the snapserver and modify the mopidy output, it streams to my clients but the playlist just stops after the first song.
Not sure if its me, what is your output for mopidy? And, I havent figured out how to stream to the clients, yet, still use the audio output from the RPI with raveberry installed.

**Comment by mxpowe** [comment]
Ok, i retested this.
I did a fresh install of raveberry, tested youtube and it works as normal.
Installed snapcast and edited the mopidy.conf to
#output = rgvolume ! audioconvert ! audioresample ! pulsesink server=127.0.0.1
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink loca$

And it works.
I then added my spotify credentials and enabled spotify, and the playlist will not play, it skips all the songs. 

When I replace output with the old setting, the functionalty returns, but kills the spotify.

**Comment by mxpowe** [comment]
output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfi$

With that in modipy, i can re-enable snapchat, but the song ends and the playlist stops.

/shrug

**Comment by raveberry** [comment]
I use the output value from [snapcasts documentation](https://github.com/badaix/snapcast/blob/master/doc/player_setup.md#mopidy):
`rgvolume ! audioconvert ! audioresample ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo`
(convert and resample swapped because audio normalization is used according to [this thread](https://discourse.mopidy.com/t/replay-gain-in-mopidy/3058/7))

I just tested with Spotify and have no problems with that either.
When setting the credentials via the web UI, Raveberry overwrites the mopidy config, including the output value. But since you re-enabled snapcast afterwards I assume you already found out.
Did you restart mopidy after each config change? Does mopidy say anything in its logs?

The issue with all songs being skipped really bothers me. It happens in rare occasions where mopidy enters a failed state but still accepts new songs. It is especially frustrating when a large list of songs is lost from this bug. I hope to find a solution some time to prevent this.

Making mopidy output to multiple sinks is possible with the `tee` directive:
`output = audioconvert ! audioresample ! tee name=t ! queue ! audio/x-raw,rate=48000,channels=2,format=S16LE ! filesink location=/tmp/snapfifo t. ! queue ! pulsesink server=127.0.0.1`

I did not see this as a frequent use case, as audio streaming usually implies a remote audience, making local playback unnecessary. With the new audio output configuration (next release) however, it should be no problem to add "icecast + local" and "snapcast + local", which would each use the previously set local output as well. Would this help you?

**Comment by mxpowe** [comment]
"If you take a look into /opt/raveberry/core/musiq/controller.py you will see the function set_volume. The except block is exactly what you want, so you can delete the try block and see if it works (beware of indentation). A systemctl restart daphne is required afterwards."

I tried this yet failed miserably lol.
I deleted the try and kept getting errors :( 
Not a big deal, just would be nice to control volume on the cast with the slider.

**Comment by mxpowe** [comment]
"The issue with all songs being skipped really bothers me. It happens in rare occasions where mopidy enters a failed state but still accepts new songs. "

It works now, the following day I was looking at the logs and noticed that spotify wasnt authenticating, I deleted the credentials and went to authorise mopidy again and the authentication url they us for the key was down. This caused the playlist to skip the songs. 

Later on the server was back online and mopidy was able to authenticate, raveberry worked as normal. I believe my issue might have been not being able to authenticate all along.

**Comment by raveberry** [comment]
snapcast output is now an option in Raveberry 0.8.5.

I tested a method to detect errors in mopidy and restart it if necessary, but I'm not quite convinced yet that it doesn't cause more harm than good in some cases. That's why its not part of the code, but maybe I will add it some time. Still great that you could resolve your issue.

Having the volume slider control mopidy's volume when streaming is a good idea, as it currently does nothing in this case. Until this is implemented, you can `apt install mopidy-mpd mpc` and then control mopidy's volume with `mpc volume 50`.
