### ISSUE TITLE
Feature request:  Fault tolerance / keep alive

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#78]
Maybe have the ability to clear the 'current song' and reboot daphne/mopidy from a single button for  mods/admin?   Otherwise, in my experience, it will just sit there in silence.

**Comment by raveberry** [comment]
In what circumstances do you encounter these situations where a restart is necessary?

Raveberry does have some kind of fault recovery. If you restart daphne, it will resume the song at the correct posiition. Since mopidy keeps on playing the song, this results in a barely noticeable pause shortly after the server has restarted.
mopidy currently needs to be restarted manually. From my experience, this is rarely the case.
daphne already has a button in the settings that reboots it (it is called "Reboot server").

**Comment by tiny-e** [comment]
The issue I always seem to have is likely related to the skip issue.  I may try a fresh-fresh reinstall and see what I get.  Mopidy get's hung up on a song and I have to go in an manually delete it form the 'current song' field, then restart it.

**Comment by champagj** [comment]
I might have encounter similar issue. Currently in early stage testing various config. I had a  Soundcloud song of 1hr in lenght in the current song and upon reboot experienced issues with the song not restarting and trying to queue the next one.
Had to use the admin panel to clear.
Ill test to see if i can reproduce.  Could issue be linked to larger files?

**Comment by raveberry** [comment]
Ideally, this kind of reset is not needed very often. I do see the your point though. As a quickfix, you can change one of the scripts in `/usr/local/sbin/raveberry/` (my suggestions would be `shutdown_system`) to do this instead:
```
sudo -u postgres psql -d raveberry -c "DELETE FROM core_currentsong;"
systemctl restart mopidy
systemctl restart daphne
```
Now the corresponding button should perform the required steps to reset the current song.

@champagj: The cause for your problem is pretty certainly a different one. It might have something to do with the soundcloud backend not being able to play the song. You will find more info in mopidy's log: `journalctl -xeu mopidy`.
Please open another issue with the logs so we can discuss these topics separately.

**Comment by tiny-e** [comment]
> Ideally, this kind of reset is not needed very often. I do see the your point though. As a quickfix, you can change one of the scripts in `/usr/local/sbin/raveberry/` (my suggestions would be `shutdown_system`) to do this instead:
> 
> ```
> sudo -u postgres psql -d raveberry -c "DELETE FROM core_currentsong;"
> systemctl restart mopidy
> systemctl restart daphne
> ```
> 
> Now the corresponding button should perform the required steps to reset the current song.
> 
> @champagj: The cause for your problem is pretty certainly a different one. It might have something to do with the soundcloud backend not being able to play the song. You will find more info in mopidy's log: `journalctl -xeu mopidy`.
> Please open another issue with the logs so we can discuss these topics separately.

Thanks-- This is the location to use if you're installed service (system install)?

**Comment by tiny-e** [comment]
Just tried it -- It worked :)

**Comment by raveberry** [comment]
Yes, this directory contains all scripts that might require sudo permissions in a system install. Great that it works, even though I hope that we can properly fix the bug instead ;)
