### ISSUE TITLE
Hotspot:  How do I tell it which interface to use?

### ISSUE THREAD

**Issue by tiny-e** [raveberry/raveberry#83]
I have 2 WiFi interfaces:  wlan0 (built in) and wlan1 (usb dongle).   I’d like to use wlan0 for the internet connection and offer the hotspot over wlan1.

I have 0 connected to my home WiFi (or phone tether) at the time of running system-install.  It inevitably makes 0 the hotspot and connects 1 to my lan. 

If I manually edit the Configs for dnamasq, hostapd, and dhcp, I can make it use the interface I want, but I seem to lose the ability for hotspot clients to now see the internet.  (I think you call that tunneling in the setup/guide?)

I believe that previous to changing the configs (basically replacing wlan1 with wlan0) I could access the internet via the hotspot.

**Comment by raveberry** [comment]
Yes, during installation I had to make a decision which interface will become the hotspot and which connects to the internet. I decided to use the built in wlan0 as the hotspot for two reasons:
* I assumed the internal chip to be more powerful, as does not have to be connected via USB. (That was just a guess though)
* I wanted to be able to access the Pi with a power cord only. This is only possible if the internal chip serves the hotspot. It would have been possible to dynamically detect this situation and reconfigure the interfaces accordingly, but this way around it was simply the easier choice.

If you want to change the way these interfaces work on your Pi, you need to change the configs for `dnsmasq`, `hostapd`, and `dhcpcd`, as you found out correctly. In order to make Raveberry use the interfaces in the other order as well, you need to modify the scripts `list_available_ssids`, `connect_to_wifi`, `disable_tunneling` and `enable_tunneling` in `/usr/local/sbin/raveberry`.

I would recommend you to disable tunneling before changing these files so you don't have two conflicting `iptables` rules.

**Comment by tiny-e** [comment]
Excuse my iptables noobishness...  This is what's in there now (I added the enable_tunneling comment for clarity here).   Does this look rihgt
`#!/bin/bash
####enable_tunneling####
if [ "$EUID" -ne 0 ]
then echo "Please run as root"
	exit
fi
iptables -t nat -A POSTROUTING -o wlan1 -j MASQUERADE
iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
iptables-save > /etc/iptables.ipv4.nat`


As of this moment, I'm connected to the hotspot and cant see the internet.

**Comment by tiny-e** [comment]
Betting I need to change **eth0** to **wlan0**...

**Comment by raveberry** [comment]
No, you simply need to change `wlan1` to `wlan0`. In all of the files I listed, simply exchange these two interfaces.
My iptables knowledge is not rock-solid either, but it's sufficient for what I tried to accomplish (I hope). These two commands will forward any traffic arriving at the hotspot **to** the specified interface. Since you want to use `wlan0` as the internet adapter, you need to forward traffic to this device instead of `wlan1`. 
`eth0` is listed as you might want to connect your pi via a cable instead of wifi, you can keep this line as it is.

**Comment by raveberry** [comment]
This should be fixed if you manage to statically name your interfaces (https://github.com/raveberry/raveberry/issues/88).
