### ISSUE TITLE
[Request] Music EQ User Control 

### ISSUE THREAD

**Issue by Crushedice** [raveberry/raveberry#95]
Greetings. 
As i got currently some smaller speaker plugged into my Pi4 , the sound is a bit too high-tone. 

It would be awesome to have some equalizer web controls.
Shouldnt be that hard, i did read something about an alsa plugin. 

Thankyou

**Comment by raveberry** [comment]
The Raspberry Pi is (in)famous for its sound quality, it varies significantly between devices. That's why it is recommended to use an external USB sound card (not only for Raveberry).

Honestly I probably won't implement a webinterface for an equalizer. The settings for the equalizer would probably be set once, I don't think that constant adjustments are necessary. That's why I think that controlling it from the commandline directly is reasonable. Also, interfacing with commandline tools from python is always kind of awkward.

If you find a solution, please do share it so other people with the same problem can make use of it. As additional info: Raveberry uses pulseaudio, so maybe the alsa plugin won't work.

**Comment by raveberry** [comment]
I looked into it and found a tool that seems to do the job:
```
# install the equalizer
sudo apt-get install pulseaudio-equalizer
# load the required modulse into pulseaudio
echo "load-module module-dbus-protocol" | sudo tee -a /etc/pulse/system.pa
echo "load-module module-equalizer-sink sink_name=equalized" | sudo tee -a /etc/pulse/system.pa
# apply the changes by restarting pulseaudio
sudo systemctl restart pulseaudio
sleep 2
# set the output sink to the equalizer
export PULSE_SERVER=127.0.0.1
pactl set-default-sink equalized
# restart the audio player
sudo systemctl restart mopidy
# configure the equalizer
export PULSE_DBUS_SERVER="unix:path=/run/pulse/dbus-socket"
qpaeq
```
This adds a new output device `equalized` that is affected by the settings done with `qpaeq`. By setting it to be the default sink, it will also get used by Raveberry.
